name: "Test build of image when Dockerfile is changed"

on:
    push:
      paths:
      - 'Dockerfile'
      branches-ignore:
      - 'master'
    pull_request:
      paths:
      - 'Dockerfile'
    workflow_dispatch:
  
  jobs:
    rebuild-container:
      name: "Build image with cache"
      runs-on: ubuntu-18.04
      steps: