name: "Test build of image when Dockerfile is changed"

on:
    push:
      paths:
      - 'Dockerfile'
      branches-ignore:
      - 'master'
    pull_request:
      paths:
      - 'Dockerfile'
    workflow_dispatch:
  
  jobs:
    rebuild-container:
      name: "Build image with cache"
      runs-on: ubuntu-18.04
      steps:
        - 
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3.2.0
            with:
              platforms: linux/arm64
        - 
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3.8.0
        - 
            name: Checkout repository
            uses: actions/checkout@v4
        - 
    